sudo: required
language: generic
services: docker
notifications:
  email: false

before_install:
  - sudo apt-get install poppler-utils
addons:
  apt:
    update: true

script:
- docker run --mount src=$TRAVIS_BUILD_DIR/src,target=/usr/src/tex,type=bind dxjoke/tectonic-docker
  /bin/sh -c "tectonic --keep-intermediates --reruns 0 main.tex; biber main; tectonic main.tex"

after_success:
  - echo "Removing files ... "
  - mv src/main.pdf AyanBanerjee.pdf
  - mv src/index.html index.html
  - rm -rf src statics
  - rm .travis.yml README.md LICENSE
  - echo "Converting to images ..."
  - pdftoppm -jpeg AyanBanerjee.pdf AyanBanerjee -singlefile

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
