sudo: required
language: generic
services: docker
notifications:
  email: false

tex-config:
- tex-scheme=small
- push-type=none
- build-pattern=src/main.tex
- packages=preprint, titlesec, marvosym, enumitem

script:
- docker pull strauman/travis-latexbuild:small # select small texlive scheme
- docker run --mount src=$TRAVIS_BUILD_DIR/,target=/repo,type=bind strauman/travis-latexbuild:small # also it here

after_success:
  - echo "Removing files ... "
  - mv src/main.pdf AyanBanerjee.pdf
  - mv src/index.html index.html
  - rm -rf src statics
  - rm .travis.yml README.md LICENSE

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
