name: Create PDF and Image

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Print dir tree
      run: find . | sed -e "s/[^-][^\/]*\// |/g" -e "s/|\([^ ]\)/|-\1/"
    - name: Install from apt
      run: sudo apt-get install poppler-utils
    - name: Create PDF
      run: |
        ls
        docker run --mount src=$GITHUB_WORKSPACE/src,target=/usr/src/tex,type=bind dxjoke/tectonic-docker
        /bin/sh -c "tectonic --keep-intermediates --reruns 0 main.tex; biber main; tectonic main.tex"
    - name: Cleanup
      run: |
        echo "Removing files ... "
        mv src/main.pdf AyanBanerjee.pdf
        mv src/index.html index.html
        rm -rf src statics
        rm .travis.yml README.md LICENSE
    - name: Convert to image
      run: |
        echo "Converting to images ..."
        pdftoppm -jpeg AyanBanerjee.pdf AyanBanerjee -singlefile
    - name: Commit to gh-pages
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git add .
        git commit -m "Create PDF and image"
        git push origin gh-pages
